apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 982009233494.dkr.ecr.ap-south-1.amazonaws.com/simplebank:e8d1e9c01e4584a800051fac9e6282e894c7442d
          ports:
            - containerPort: 8080
          
